on: [push]

jobs:
  upstream_pr:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
        if: ${{ env.ACT }}
        with:
          path: "action-upstream-to-pr" # bug: https://github.com/RobotsAndPencils/1password-action/pull/46
      - name: View contents
        run: pwd && ls -al     
      - name: Hello world action step (LOCAL)
        if: ${{ env.ACT }}
        uses: ./action-upstream-to-pr
        id: hello-local
        with:
          who-to-greet: 'Mona the Octocat'
      - name: Hello world action step
        if: ${{ !env.ACT }}
        uses: ./ # Uses an action in the root directory
        id: hello-prod
        with:
          who-to-greet: 'Mona the Octocat'          
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"